apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    adhoc: khushiq7   
  name: adhocpod7
spec:
  volumes:    
  - name: vol123   
    emptyDir: {}    
  containers:
  - image: alpine
    name: adhocpod7
    volumeMounts:
    - name: vol123  
      mountPath: /mnt/date.txt/   
    command: ["/bin/sh","-c","while true ; do date  >>/mnt/date.txt/adhocoutput.txt;sleep 2;done"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
